console.log('Hello World!')
console.log('Added this line!')
console.log('Added another line!')
console.log("foo bar")
console.log("foo bar again")
console.log("Testing for creating branches")
console.log("Looking for new branch")